name: sharpsell_store
description: "Sharpsell Store - E-commerce application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  # Dependency injection
  get_it: ^7.6.4
  # Network
  dio: ^5.3.3
  internet_connection_checker: ^1.0.0+1
  # Storage
  shared_preferences: ^2.2.2
  # Utilities
  uuid: ^4.2.1
  # UI
  cached_network_image: ^3.3.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/